kind: Pod
apiVersion: v1
metadata:
  name: nfs-in-a-pod3
spec:
  containers:
    - name: app
      image: alpine
      volumeMounts:
        - name: nfs-volume
          mountPath: /var/nfs
      command: ["/bin/sh"]
      args: ["-c", "sleep 500000"]
  volumes:
    - name: nfs-volume
      nfs:
        server: "44.211.213.216"
        path: /nfs-datadir/data

